INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Stargazing', 'Myles Smith', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'I Don\'t Wanna Wait', 'David Guetta x OneRepublic', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Flashback', 'ÁSDÍS', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Feels Like I\'m Falling In Love', 'Coldplay', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Austin (Boots Stop Workin\')', 'Dasha', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Belong Together', 'Mark Ambor', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Espresso', 'Sabrina Carpenter', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Fire', 'Meduza x OneRepublic x Leony', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'So Good', 'Kamrad', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Fortnight', 'Taylor Swift feat. Post Malone', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'A Bar Song (Tipsy)', 'Shaboozey', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Shut Up And Dance', 'Sophie and the Giants', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Head Down', 'Lost Frequencies x Bastille', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Beautiful Reason', 'Michael Schulte', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Illusion', 'Dua Lipa', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Out My Head', 'Topic x A7S', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Beat Of Your Heart', 'Purple Disco Machine x ÁSDÍS', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Piano', 'Kelvin Jones', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Too Sweet', 'Hozier', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Simple Life', 'Leony', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Stumblin\' In', 'Cyril', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Glow In The Dark', 'Tom Gregory', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Whatever', 'Kygo x Ava Max', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Honey Boy', 'Purple Disco Machine x Bejamin Ingrosso feat. Nile Rodgers', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Heard It All', 'Iggi Kelly', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'All In', 'YouNotUs x Laurell', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Te Imaginaba', 'Alvaro Soler', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Always On The Run', 'Isaak', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Never Be Lonely', 'Jax Jones x Zoe Wees', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Love U Again', 'ClockClock', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'The Way I Want It', 'Loi', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Magic Moment', 'Glockenbach x Chris de Sarandy', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Promise', 'Malik Harris', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Summer\'s Back', 'Alok x Jess Glynne', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'My Oh My', 'Ava Max', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Electricity', 'Fast Boy x R3hab', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Loyal To Myself', 'Lena', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Lunch', 'Billie Eilish', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Gimme Your Hand', 'Samu Haber', 30, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Woman\'s World', 'Katy Perry', 30, 2024);
