INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Why Why Why', 'Shawn Mendes', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Someday Soon', 'ClockClock', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Wave', 'Fast Boy x Raf', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Austin (Boots Stop Workin\')', 'Dasha', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Human Being', 'Nico Santos', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Belong Together', 'Mark Ambor', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Halo', 'Rea Garvey', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Dancing In The Flames', 'The Weeknd', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Woman\'s World', 'Katy Perry', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'We Pray', 'Coldplay x Little Simz x Burna Boy x Elyanna x TINI', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Shut Up And Dance', 'Sophie and the Giants', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Roots', 'Calum Scott', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Birds Of A Feather', 'Billie Eilish', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Better Days', 'Glockenbach feat. Declan J Donovan', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Feels Like I\'m Falling In Love', 'Coldplay', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Te Imaginaba', 'Alvaro Soler', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'A Bar Song (Tipsy)', 'Shaboozey', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Black Friday (Pretty Like The Sun)', 'Tom Odell x Lost Frequencies', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Taste', 'Sabrina Carpenter', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Blood Sweat Tears', 'Riku Rajamaa', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'All In', 'YouNotUs x Laurell', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Summer\'s Back', 'Alok x Jess Glynne', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Beautiful Reason', 'Michael Schulte', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Friends', 'Kamrad', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Tears To Stay', 'Ray Dalton', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Spot A Fake', 'Ava Max', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'The Way I Want It', 'Loi', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Die With A Smile', 'Lady Gaga & Bruno Mars', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Stargazing', 'Myles Smith', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'All Night', 'R3hab & Sophie and the Giants', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Bad Dreams', 'Teddy Swims', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Good Luck Babe!', 'Chappel Roan', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Espresso', 'Sabrina Carpenter', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Sink Or Swim', 'OneRepublic', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Never Going Home Tonight', 'David Guetta & Alesso feat. Madison Love', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'I Like The Way You Kiss Me', 'Artemas', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Flashback', 'ÁSDÍS', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Glow In The Dark', 'Tom Gregory', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Rain', 'Chris de Sarandy', 43, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Fortnight', 'Taylor Swift feat. Post Malone', 43, 2024);
