INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Dancing In The Flames', 'The Weeknd', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Why Why Why', 'Shawn Mendes', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Someday Soon', 'ClockClock', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Halo', 'Rea Garvey', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Taste', 'Sabrina Carpenter', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Wave', 'Fast Boy x Raf', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Human Being', 'Nico Santos', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'We Pray', 'Coldplay x Little Simz x Burna Boy x Elyanna x TINI', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Austin (Boots Stop Workin\')', 'Dasha', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Shut Up And Dance', 'Sophie and the Giants', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Friends', 'Kamrad', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Better Days', 'Glockenbach feat. Declan J Donovan', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Spot A Fake', 'Ava Max', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Belong Together', 'Mark Ambor', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'A Bar Song (Tipsy)', 'Shaboozey', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'The Way I Want It', 'Loi', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Roots', 'Calum Scott', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Birds Of A Feather', 'Billie Eilish', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Bad Dreams', 'Teddy Swims', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'All My Life', 'Purple Disco Machine x The Magician', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Woman\'s World', 'Katy Perry', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Te Imaginaba', 'Alvaro Soler', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Feels Like I\'m Falling In Love', 'Coldplay', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Beautiful Reason', 'Michael Schulte', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Blood Sweat Tears', 'Riku Rajamaa', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Never Going Home Tonight', 'David Guetta & Alesso feat. Madison Love', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Die With A Smile', 'Lady Gaga & Bruno Mars', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Black Friday (Pretty Like The Sun)', 'Tom Odell x Lost Frequencies', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'It’s ok I’m ok', 'Tate McRae', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'All In', 'YouNotUs x Laurell', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Stars Will Align', 'Kygo x Imagine Dragons', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Summer\'s Back', 'Alok x Jess Glynne', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'I Like The Way You Kiss Me', 'Artemas', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Stargazing', 'Myles Smith', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Sink Or Swim', 'OneRepublic', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Good Luck Babe!', 'Chappel Roan', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Rain', 'Chris de Sarandy', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Tears To Stay', 'Ray Dalton', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Crazy For You', 'Milow', 45, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Flashback', 'ÁSDÍS', 45, 2024);
