INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Beat Of Your Heart', 'Purple Disco Machine x ÁSDÍS', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Head Down', 'Lost Frequencies x Bastille', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Stumblin\' In', 'Cyril', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'All We Got', 'Ray Dalton', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Whatever', 'Kygo x Ava Max', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Houdini', 'Dua Lipa', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Selfish', 'Justin Timberlake', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Always On The Run', 'Isaak', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Texas Hold Em', 'Beyoncé', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Overdrive', 'Ofenbach feat. Norma Jean Martine', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Never Be Lonely', 'Jax Jones x Zoe Wees', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Waking Up', 'Felix Jaehn & Leony', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'So Good', 'Kamrad', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Where You Are', 'Fast Boy x Nico Santos', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Yes And?', 'Ariana Grande', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Beautiful Things', 'Benson Boone', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'I\'ll Be There', 'Robin Schulz & Rita Ora & Tiago PZK', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Training Season', 'Dua Lipa', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Magic Moment', 'Glockenbach x Chris de Sarandy', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Simple Life', 'Leony', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Heard It All', 'Iggi Kelly', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Strangers', 'Kenya Grace', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Am I Enough', 'Loi', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Know That You\'re Not Alone', 'Catburns', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Lovers In A Past Life', 'Calvin Harris x Rag\'n\'Bone Man', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Somewhere Close To Heaven', 'Rea Garvey x Picture This', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Love Hurt Repeat', 'Alle Farben x Lewis Thompson feat. Mae Muller', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'All Night Long', 'Kungs x David Guetta & Izzy Bizu', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Love U Again', 'ClockClock', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Is It Over Now? (Taylor\'s Version)', 'Taylor Swift', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Lose Control', 'Teddy Swims', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Memory Lane', 'Zara Larsson', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Gimme Love', 'Sia', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Gimme Your Hand', 'Samu Haber', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Greedy', 'Tate McRae', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Good To Be', 'Mark Ambor', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Hungry Heart', 'Declan J Donovan', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Can\'t Get Enough', 'Jennifer Lopez', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'We Can\'t Be Friends (Wait For Your Love)', 'Ariana Grande', 14, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Head Underwater', 'Tom Walker', 14, 2024);
