INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Dancing In The Flames', 'The Weeknd', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Friends', 'Kamrad', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Taste', 'Sabrina Carpenter', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Halo', 'Rea Garvey', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Someday Soon', 'ClockClock', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Wave', 'Fast Boy x Raf', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Why Why Why', 'Shawn Mendes', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'We Pray', 'Coldplay x Little Simz x Burna Boy x Elyanna x TINI', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Human Being', 'Nico Santos', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Spot A Fake', 'Ava Max', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Bad Dreams', 'Teddy Swims', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Austin (Boots Stop Workin\')', 'Dasha', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Better Days', 'Glockenbach feat. Declan J Donovan', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'The Way I Want It', 'Loi', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'A Bar Song (Tipsy)', 'Shaboozey', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Shut Up And Dance', 'Sophie and the Giants', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Belong Together', 'Mark Ambor', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Woman\'s World', 'Katy Perry', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Birds Of A Feather', 'Billie Eilish', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Stars Will Align', 'Kygo x Imagine Dragons', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Die With A Smile', 'Lady Gaga & Bruno Mars', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Rock N Roll', 'Leony x G-Eazy', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Feels Like I\'m Falling In Love', 'Coldplay', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Wreck', 'Tom Gregory', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'All My Life', 'Purple Disco Machine x The Magician', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Te Imaginaba', 'Alvaro Soler', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Roots', 'Calum Scott', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'I Like The Way You Kiss Me', 'Artemas', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Beautiful Reason', 'Michael Schulte', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Black Friday (Pretty Like The Sun)', 'Tom Odell x Lost Frequencies', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Ray Of Light', 'Nico Santos', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'It’s ok I’m ok', 'Tate McRae', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'All In', 'YouNotUs x Laurell', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Crazy For You', 'Milow', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Call My Name', 'Alle Farben feat. Sofiloud', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Never Going Home Tonight', 'David Guetta & Alesso feat. Madison Love', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Sink Or Swim', 'OneRepublic', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Rain', 'Chris de Sarandy', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'World Gone Wild', 'Robin Schulz x Cyril feat. Sam Martin', 47, 2024);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Stargazing', 'Myles Smith', 47, 2024);
