INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Azizam', 'Ed Sheeran', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Million Good Reasons', 'Robin Schulz x Fast Boy', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Ordinary', 'Alex Warren', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Sorry I\'m Here For Someone Else', 'Benson Boone', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'By Your Side (In My Mind)', 'Leony', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Chasing Paradise', 'Kygo x OneRepublic', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Nice To Meet You', 'Myles Smith', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Abracadabra', 'Lady Gaga', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'That\'s So True', 'Gracie Abrams', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Slow Motion', 'Marshmello x Jonas Brothers', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Flowers', 'Alle Farben x Graham Candy x Lahos', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Messy', 'Lola Young', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Forever Young', 'David Guetta x Alphaville x Ava Max', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'End Of The World', 'Miley Cyrus', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Show Me Love', 'WizTheMc', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'APT.', 'Rosé & Bruno Mars', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Ray Of Light', 'Nico Santos', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Anthem', 'Glockenbach feat. Norma Jean Martine', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Broken Sunshine', 'Michael Schulte', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Beautiful People', 'David Guetta & Sia', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Rebellion', 'R3hab x Michael Patrick Kelly x Shaggy', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Thee Unknown', 'Ray Dalton', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Touch Me', 'ÁSDÍS', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'A Bar Song (Tipsy)', 'Shaboozey', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Con Calma', 'Alvaro Soler', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Walk With Me', 'Felix Jaehn x Shouse', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Bad Dreams', 'Teddy Swims', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Traitor', 'Zoe Wees', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Afterlife', 'Michael Schulte', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Born Again', 'Fast Boy & ClockClock', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Castaways', 'Milow feat. Florence Arman', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Born Again', 'Lisa x Doja Cat x Raye', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Glide', 'Neiked x Portugal The Man', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Austin (Boots Stop Workin\')', 'Dasha', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Dancing In The Flames', 'The Weeknd', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Anxiety', 'Doechii', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Blink Twice', 'Shaboozey feat. Myles Smith', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Control Of Me', 'Topic x Daecolm', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'The One', 'Michael Patrick Kelly', 20, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Better Days', 'Glockenbach feat. Declan J Donovan', 20, 2025);
