INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Forever Young', 'David Guetta x Alphaville x Ava Max', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Ray Of Light', 'Nico Santos', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Rock N Roll', 'Leony x G-Eazy', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Love Is The Only Thing', 'Lost Frequencies', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'A Bar Song (Tipsy)', 'Shaboozey', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Forbidden Road', 'Robbie Williams', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Someday Soon', 'ClockClock', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Broken Sunshine', 'Michael Schulte', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Wave', 'Fast Boy x Raf', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Touch Me', 'ÁSDÍS', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Better Days', 'Glockenbach feat. Declan J Donovan', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Friends', 'Kamrad', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Stars Will Align', 'Kygo x Imagine Dragons', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Thee Unknown', 'Ray Dalton', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Spot A Fake', 'Ava Max', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Bad Dreams', 'Teddy Swims', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'All My Life', 'Purple Disco Machine x The Magician', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'That\'s So True', 'Gracie Abrams', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Human Being', 'Nico Santos', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', '2 Hands', 'Tate McRae', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Dancing In The Flames', 'The Weeknd', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Nice To Meet You', 'Myles Smith', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'I Adore You', 'HUGEL x Topic x Arash feat. Daecolm', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Austin (Boots Stop Workin\')', 'Dasha', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'The Way I Want It', 'Loi', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Taste', 'Sabrina Carpenter', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Houdini', 'Eminem', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Left In Your Love', 'Loi', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Walk With Me', 'Felix Jaehn x Shouse', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Too Sweet', 'Hozier', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'By Your Side (In My Mind)', 'Leony', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'The Emptiness Machine', 'Linkin Park', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Shut Up And Dance', 'Sophie and the Giants', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Belong Together', 'Mark Ambor', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Halo', 'Rea Garvey', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Stargazing', 'Myles Smith', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Traitor', 'Zoe Wees', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'We Pray', 'Coldplay x Little Simz x Burna Boy x Elyanna x TINI', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Someone For Me', 'Kylie Minogue & YouNotUs', 7, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Birds Of A Feather', 'Billie Eilish', 7, 2025);
