INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'By Your Side (In My Mind)', 'Leony', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Ray Of Light', 'Nico Santos', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Forever Young', 'David Guetta x Alphaville x Ava Max', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Nice To Meet You', 'Myles Smith', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Touch Me', 'ÁSDÍS', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Chasing Paradise', 'Kygo x OneRepublic', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'That\'s So True', 'Gracie Abrams', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Thee Unknown', 'Ray Dalton', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'A Bar Song (Tipsy)', 'Shaboozey', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Someday Soon', 'ClockClock', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Love Is The Only Thing', 'Lost Frequencies', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Broken Sunshine', 'Michael Schulte', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Better Days', 'Glockenbach feat. Declan J Donovan', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Traitor', 'Zoe Wees', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Wave', 'Fast Boy x Raf', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Rock N Roll', 'Leony x G-Eazy', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Bad Dreams', 'Teddy Swims', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Dancing In The Flames', 'The Weeknd', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Messy', 'Lola Young', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Walk With Me', 'Felix Jaehn x Shouse', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Austin (Boots Stop Workin\')', 'Dasha', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Slow Motion', 'Marshmello x Jonas Brothers', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Million Good Reasons', 'Robin Schulz x Fast Boy', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Forbidden Road', 'Robbie Williams', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'The Emptiness Machine', 'Linkin Park', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Left In Your Love', 'Loi', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'All My Life', 'Purple Disco Machine x The Magician', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Spot A Fake', 'Ava Max', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Too Sweet', 'Hozier', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Castaways', 'Milow feat. Florence Arman', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Houdini', 'Eminem', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Flowers', 'Alle Farben x Graham Candy x Lahos', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Born Again', 'Lisa x Doja Cat x Raye', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Human Being', 'Nico Santos', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'APT.', 'Rosé & Bruno Mars', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Lost Your Faith', 'Ava Max', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'I Adore You', 'HUGEL x Topic x Arash feat. Daecolm', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Rebellion', 'R3hab x Michael Patrick Kelly x Shaggy', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Guilty', 'Teddy Swims', 12, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Belong Together', 'Mark Ambor', 12, 2025);
