INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Ray Of Light', 'Nico Santos', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Forever Young', 'David Guetta x Alphaville x Ava Max', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Touch Me', 'ÁSDÍS', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'A Bar Song (Tipsy)', 'Shaboozey', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'That\'s So True', 'Gracie Abrams', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Better Days', 'Glockenbach feat. Declan J Donovan', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'By Your Side (In My Mind)', 'Leony', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Love Is The Only Thing', 'Lost Frequencies', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Broken Sunshine', 'Michael Schulte', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Wave', 'Fast Boy x Raf', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Chasing Paradise', 'Kygo x OneRepublic', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Bad Dreams', 'Teddy Swims', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Nice To Meet You', 'Myles Smith', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Someday Soon', 'ClockClock', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Thee Unknown', 'Ray Dalton', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Dancing In The Flames', 'The Weeknd', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Austin (Boots Stop Workin\')', 'Dasha', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Traitor', 'Zoe Wees', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Rock N Roll', 'Leony x G-Eazy', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Forbidden Road', 'Robbie Williams', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Spot A Fake', 'Ava Max', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Messy', 'Lola Young', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'The Emptiness Machine', 'Linkin Park', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Slow Motion', 'Marshmello x Jonas Brothers', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Walk With Me', 'Felix Jaehn x Shouse', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Million Good Reasons', 'Robin Schulz x Fast Boy', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Too Sweet', 'Hozier', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'All My Life', 'Purple Disco Machine x The Magician', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Houdini', 'Eminem', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Left In Your Love', 'Loi', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'I Adore You', 'HUGEL x Topic x Arash feat. Daecolm', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'APT.', 'Rosé & Bruno Mars', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Castaways', 'Milow feat. Florence Arman', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Flowers', 'Alle Farben x Graham Candy x Lahos', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Belong Together', 'Mark Ambor', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Born Again', 'Lisa x Doja Cat x Raye', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Human Being', 'Nico Santos', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Friends', 'Kamrad', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Rebellion', 'R3hab x Michael Patrick Kelly x Shaggy', 11, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Birds Of A Feather', 'Billie Eilish', 11, 2025);
