INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Forever Young', 'David Guetta x Alphaville x Ava Max', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Ray Of Light', 'Nico Santos', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Touch Me', 'ÁSDÍS', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Broken Sunshine', 'Michael Schulte', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Rock N Roll', 'Leony x G-Eazy', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Forbidden Road', 'Robbie Williams', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Love Is The Only Thing', 'Lost Frequencies', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'A Bar Song (Tipsy)', 'Shaboozey', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Someday Soon', 'ClockClock', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Spot A Fake', 'Ava Max', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Wave', 'Fast Boy x Raf', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Bad Dreams', 'Teddy Swims', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Better Days', 'Glockenbach feat. Declan J Donovan', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'That\'s So True', 'Gracie Abrams', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Friends', 'Kamrad', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Thee Unknown', 'Ray Dalton', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Stars Will Align', 'Kygo x Imagine Dragons', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Human Being', 'Nico Santos', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Houdini', 'Eminem', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Austin (Boots Stop Workin\')', 'Dasha', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'I Adore You', 'HUGEL x Topic x Arash feat. Daecolm', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Left In Your Love', 'Loi', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', '2 Hands', 'Tate McRae', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Dancing In The Flames', 'The Weeknd', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'By Your Side (In My Mind)', 'Leony', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Walk With Me', 'Felix Jaehn x Shouse', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Nice To Meet You', 'Myles Smith', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'The Emptiness Machine', 'Linkin Park', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Too Sweet', 'Hozier', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Taste', 'Sabrina Carpenter', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'The Way I Want It', 'Loi', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Belong Together', 'Mark Ambor', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Traitor', 'Zoe Wees', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'APT.', 'Rosé & Bruno Mars', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Chasing Paradise', 'Kygo x OneRepublic', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Someone For Me', 'Kylie Minogue & YouNotUs', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Birds Of A Feather', 'Billie Eilish', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Halo', 'Rea Garvey', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Slow Motion', 'Marshmello x Jonas Brothers', 8, 2025);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'All My Life', 'Purple Disco Machine x The Magician', 8, 2025);
