INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Strangers', 'Kenya Grace', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Greedy', 'Tate McRae', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Lifeline', 'Glockenbach x Ella Henderson', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'The Feeling', 'Lost Frequencies', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Gimme Love', 'Sia', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'I\'ll Be There', 'Robin Schulz & Rita Ora & Tiago PZK', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Better Me', 'Michael Schulte x R3hab', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Cynical', 'twocolors x SafriDuo x Chris de Sarandy', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Overdrive', 'Ofenbach feat. Norma Jean Martine', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Cruel Summer', 'Taylor Swift', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Seasons', 'Thirty Seconds To Mars', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Angel Eyes', 'ÁSDÍS', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'I Hope You End Up Alone (With Me)', 'Kamrad', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Paradise', 'Sophie and The Giants x Purple Disco Machine', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Runaway', 'OneRepublic', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Houdini', 'Dua Lipa', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Blindside', 'James Arthur', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Runaway', 'P!nk', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Free Like The Ocean', 'Rea Garvey', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Single Soon', 'Selena Gomez', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Where You Are', 'Fast Boy x Nico Santos', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Sticks & Stones', 'Malik Harris', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Something On My Mind', 'Purple Disco Machine x Duke Dumont x Nothing But Thieves', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Dreaming', 'Marshmello x P!nk x Sting', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'American Town', 'Ed Sheeran', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Lightning', 'Zoe Wees', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Past Life', 'Felix Jaehn & Jonas Blue', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Wanna Dance', 'Alle Farben & James Carter & VARGEN', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Changes', 'Nico Santos & ClockClock', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'O.K.O', 'Michael Patrick Kelly', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Dive', 'Lost Frequencies & Tom Gregory', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Baby Don\'t Hurt Me', 'David Guetta x Anne-Marie x Coi Leray', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Better Place', '*NSYNC x Justin Timberlake', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Alive', 'Toby Romeo x Declan J Donovan', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Lay Low', 'Tiësto', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Substitution', 'Purple Disco Machine x Kungs x Julian Perretta', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Miracle', 'Tors', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Waterfall', 'Michael Schulte x R3hab', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Perfect In My Eyes', 'Rea Garvey', 48, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Jaded', 'Miley Cyrus', 48, 2023);
