INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Greedy', 'Tate McRae', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Gimme Love', 'Sia', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Houdini', 'Dua Lipa', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Better Me', 'Michael Schulte x R3hab', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Strangers', 'Kenya Grace', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Overdrive', 'Ofenbach feat. Norma Jean Martine', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'I\'ll Be There', 'Robin Schulz & Rita Ora & Tiago PZK', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'The Feeling', 'Lost Frequencies', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Lifeline', 'Glockenbach x Ella Henderson', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Angel Eyes', 'ÁSDÍS', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Cruel Summer', 'Taylor Swift', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Cynical', 'twocolors x SafriDuo x Chris de Sarandy', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Sticks & Stones', 'Malik Harris', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Dreaming', 'Marshmello x P!nk x Sting', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Paradise', 'Sophie and The Giants x Purple Disco Machine', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Blindside', 'James Arthur', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Where You Are', 'Fast Boy x Nico Santos', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'I Hope You End Up Alone (With Me)', 'Kamrad', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Seasons', 'Thirty Seconds To Mars', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Runaway', 'P!nk', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Perfect In My Eyes', 'Rea Garvey', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Runaway', 'OneRepublic', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Something On My Mind', 'Purple Disco Machine x Duke Dumont x Nothing But Thieves', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Past Life', 'Felix Jaehn & Jonas Blue', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Am I Enough', 'Loi', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Single Soon', 'Selena Gomez', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'O.K.O', 'Michael Patrick Kelly', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Wanna Dance', 'Alle Farben & James Carter & VARGEN', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Free Like The Ocean', 'Rea Garvey', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Straitjacket', 'Lena', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'American Town', 'Ed Sheeran', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Lay Low', 'Tiësto', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Crazy Again', 'Gossip', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Dive', 'Lost Frequencies & Tom Gregory', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Changes', 'Nico Santos & ClockClock', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Lightning', 'Zoe Wees', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Baby Don\'t Hurt Me', 'David Guetta x Anne-Marie x Coi Leray', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Alive', 'Toby Romeo x Declan J Donovan', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Is It Over Now? (Taylor\'s Version)', 'Taylor Swift', 50, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Better Place', '*NSYNC x Justin Timberlake', 50, 2023);
