INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Greedy', 'Tate McRae', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Gimme Love', 'Sia', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Being Home', 'Antenne Bayern Allstars', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'I\'ll Be There', 'Robin Schulz & Rita Ora & Tiago PZK', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Houdini', 'Dua Lipa', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Overdrive', 'Ofenbach feat. Norma Jean Martine', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Better Me', 'Michael Schulte x R3hab', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Angel Eyes', 'ÁSDÍS', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Cynical', 'twocolors x SafriDuo x Chris de Sarandy', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'The Feeling', 'Lost Frequencies', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Lifeline', 'Glockenbach x Ella Henderson', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Strangers', 'Kenya Grace', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Dreaming', 'Marshmello x P!nk x Sting', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Cruel Summer', 'Taylor Swift', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Where You Are', 'Fast Boy x Nico Santos', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'All I Want For Christmas Is You', 'Mariah Carey', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Sticks & Stones', 'Malik Harris', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Paradise', 'Sophie and The Giants x Purple Disco Machine', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Perfect In My Eyes', 'Rea Garvey', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Past Life', 'Felix Jaehn & Jonas Blue', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Blindside', 'James Arthur', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Am I Enough', 'Loi', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'I Hope You End Up Alone (With Me)', 'Kamrad', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Runaway', 'P!nk', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Seasons', 'Thirty Seconds To Mars', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Runaway', 'OneRepublic', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Single Soon', 'Selena Gomez', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'American Town', 'Ed Sheeran', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Something On My Mind', 'Purple Disco Machine x Duke Dumont x Nothing But Thieves', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Last Christmas', 'WHAM!', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Free Like The Ocean', 'Rea Garvey', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Crazy Again', 'Gossip', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'O.K.O', 'Michael Patrick Kelly', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Wanna Dance', 'Alle Farben & James Carter & VARGEN', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Straitjacket', 'Lena', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Is It Over Now? (Taylor\'s Version)', 'Taylor Swift', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Dive', 'Lost Frequencies & Tom Gregory', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Lightning', 'Zoe Wees', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Know That You\'re Not Alone', 'Catburns', 51, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Lay Low', 'Tiësto', 51, 2023);
