INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Strangers', 'Kenya Grace', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'Greedy', 'Tate McRae', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Gimme Love', 'Sia', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Lifeline', 'Glockenbach x Ella Henderson', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'I\'ll Be There', 'Robin Schulz & Rita Ora & Tiago PZK', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'Overdrive', 'Ofenbach feat. Norma Jean Martine', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Houdini', 'Dua Lipa', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Better Me', 'Michael Schulte x R3hab', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'The Feeling', 'Lost Frequencies', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Cruel Summer', 'Taylor Swift', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Cynical', 'twocolors x SafriDuo x Chris de Sarandy', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Angel Eyes', 'ÁSDÍS', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Paradise', 'Sophie and The Giants x Purple Disco Machine', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Seasons', 'Thirty Seconds To Mars', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'I Hope You End Up Alone (With Me)', 'Kamrad', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Dreaming', 'Marshmello x P!nk x Sting', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'Blindside', 'James Arthur', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Where You Are', 'Fast Boy x Nico Santos', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Sticks & Stones', 'Malik Harris', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Past Life', 'Felix Jaehn & Jonas Blue', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Runaway', 'OneRepublic', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Something On My Mind', 'Purple Disco Machine x Duke Dumont x Nothing But Thieves', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Runaway', 'P!nk', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Single Soon', 'Selena Gomez', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Free Like The Ocean', 'Rea Garvey', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'O.K.O', 'Michael Patrick Kelly', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'Wanna Dance', 'Alle Farben & James Carter & VARGEN', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Dive', 'Lost Frequencies & Tom Gregory', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Am I Enough', 'Loi', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'Changes', 'Nico Santos & ClockClock', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Baby Don\'t Hurt Me', 'David Guetta x Anne-Marie x Coi Leray', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'American Town', 'Ed Sheeran', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Lay Low', 'Tiësto', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Lightning', 'Zoe Wees', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Alive', 'Toby Romeo x Declan J Donovan', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Perfect In My Eyes', 'Rea Garvey', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Better Place', '*NSYNC x Justin Timberlake', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Miracle', 'Tors', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Straitjacket', 'Lena', 49, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Waterfall', 'Michael Schulte x R3hab', 49, 2023);
