INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('1', 'Greedy', 'Tate McRae', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('2', 'The Feeling', 'Lost Frequencies', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('3', 'Better Me', 'Michael Schulte x R3hab', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('4', 'Lifeline', 'Glockenbach x Ella Henderson', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('5', 'Strangers', 'Kenya Grace', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('6', 'I Hope You End Up Alone (With Me)', 'Kamrad', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('7', 'Cruel Summer', 'Taylor Swift', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('8', 'Seasons', 'Thirty Seconds To Mars', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('9', 'Angel Eyes', 'ÁSDÍS', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('10', 'Single Soon', 'Selena Gomez', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('11', 'Cynical', 'twocolors x SafriDuo x Chris de Sarandy', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('12', 'Runaway', 'OneRepublic', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('13', 'Gimme Love', 'Sia', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('14', 'Overdrive', 'Ofenbach feat. Norma Jean Martine', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('15', 'Paradise', 'Sophie and The Giants x Purple Disco Machine', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('16', 'Runaway', 'P!nk', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('17', 'I\'ll Be There', 'Robin Schulz & Rita Ora & Tiago PZK', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('18', 'Blindside', 'James Arthur', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('19', 'Lightning', 'Zoe Wees', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('20', 'Free Like The Ocean', 'Rea Garvey', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('21', 'Changes', 'Nico Santos & ClockClock', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('22', 'Used To Be Young', 'Miley Cyrus', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('23', 'Dreaming', 'Marshmello x P!nk x Sting', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('24', 'Sticks & Stones', 'Malik Harris', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('25', 'Something On My Mind', 'Purple Disco Machine x Duke Dumont x Nothing But Thieves', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('26', 'Past Life', 'Felix Jaehn & Jonas Blue', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('27', 'O.K.O', 'Michael Patrick Kelly', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('28', 'Dive', 'Lost Frequencies & Tom Gregory', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('29', 'Where You Are', 'Fast Boy x Nico Santos', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('30', 'American Town', 'Ed Sheeran', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('31', 'Baby Don\'t Hurt Me', 'David Guetta x Anne-Marie x Coi Leray', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('32', 'Waterfall', 'Michael Schulte x R3hab', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('33', 'Jaded', 'Miley Cyrus', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('34', 'Lay Low', 'Tiësto', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('35', 'Alive', 'Toby Romeo x Declan J Donovan', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('36', 'Better Place', '*NSYNC x Justin Timberlake', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('37', 'Somebody Like You', 'Giant Rooks', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('38', 'Substitution', 'Purple Disco Machine x Kungs x Julian Perretta', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('39', 'Miracle', 'Tors', 47, 2023);
INSERT INTO `top40` (`Platz`, `Titel`, `Interpret`, `kw`, `jahr`) VALUES ('40', 'Dance The Night', 'Dua Lipa', 47, 2023);
